name: flutter_audio_tagger
description: "A Flutter plugin for reading and editing audio file metadata (tags) with support for multiple audio formats."
version: 4.0.4
homepage: https://github.com/vrtkarim/flutter_audio_tagger

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.creadv.flutter_audio_tagger
        pluginClass: FlutterAudioTaggerPlugin

  